### ISSUE TITLE
Item disappear if I move it to chest in 1.2

### ISSUE THREAD

**Issue by PetteriM1** [Creeperface01/Nukkit#25]

**Comment by Creeperface01** [comment]
steps to reproduce?

**Comment by PetteriM1** [comment]
Get item example dirt block and try to move it to chest. Last tested yesterday with Minecraft Windows 10.

**Comment by KatyushaScarlet** [comment]
I also have this problem on 1.2.0 and 1.2.1

**Comment by ghost** [comment]
I also have this problem

**Comment by ghost** [comment]
This is a very serious problem
![mcsgx6 ds4ukobll 03q pl](https://user-images.githubusercontent.com/16436412/31129899-775760e8-a888-11e7-9a95-895f314802c7.jpg)

**Comment by Creeperface01** [comment]
be more specific next time, it only affects large chests
