### ISSUE TITLE
Other than flat world chunks not load for other players

### ISSUE THREAD

**Issue by PetteriM1** [Creeperface01/Nukkit#26]

**Comment by Creeperface01** [comment]
steps to reproduce? I cannot reproduce it

**Comment by PetteriM1** [comment]
I don't know. For me it works fine on my server but other players have reported that survival world doesn't load.

**Comment by PetteriM1** [comment]
This problem was also before 1.2

**Comment by Creeperface01** [comment]
I cannot reproduce it

**Comment by PetteriM1** [comment]
If you want to come to check my server ip is suomicraftpe.ddns.net:19132
