### ISSUE TITLE
Problem with Multiversion

### ISSUE THREAD

**Issue by Meszpo** [Creeperface01/Nukkit#58]
**Hi CreeperFace!** 
I wana to join from 1.1.5 to my server ( i use your's multiversion project ) and i have this error...
https://hastebin.com/yubuvebeca.bash
Can you help me? or anyone else?

**Comment by Creeperface01** [comment]
Because this works only with my fork of synapse and nemisys

**Comment by Meszpo** [comment]
So I can not use it?

**Comment by Creeperface01** [comment]
Only with my fork of synapse and nemisys

**Comment by Mespeczek** [comment]
@Creeperface01 Can you give me your folk and can you instruct me how to properly install this engine on vps

**Comment by Mespeczek** [comment]
@Creeperface01 Can you tell me What I must do that the multiverse would work?
